"""Regenerate the species block of the provenance ledger from the species tables.

The ledger ``docs/provenance/ledger.yaml`` (PLAN.md Section 14.5) is hand-maintained except for the block
between the BEGIN/END markers below, which this tool rewrites from every ``Cited`` constant in
``qutip_trap.species.MODULES`` so that the ledger and the tables cannot drift apart (``tests/test_provenance.py``
asserts the block is current).

    uv run python tools/ledger_from_tables.py            # rewrite in place
    uv run python tools/ledger_from_tables.py --check    # exit 1 if the block is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from qutip_trap.provenance import Cited, ledger_path
from qutip_trap.species import MODULES

BEGIN = "# --- BEGIN species constants (generated by tools/ledger_from_tables.py; do not edit by hand) ---"
END = "# --- END species constants ---"


def _yaml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _record(species_name: str, c: Cited) -> str:
    symbol = c.ledger_id.split(".", 1)[1]
    unit = f" [{c.unit}]" if c.unit else ""
    unc = f" +- {c.uncertainty!r}" if c.uncertainty is not None else ""
    equation = f"{symbol} = {c.value!r}{unit}{unc}"
    lines = [
        f"  - id: {_yaml_str(c.ledger_id)}",
        f"    symbol: {_yaml_str(symbol)}",
        f"    tag: {_yaml_str(c.tag)}",
        f"    section: {_yaml_str('4.5.6 species table ' + species_name)}",
        f"    source: {_yaml_str(c.source)}",
        f"    equation: {_yaml_str(equation)}",
        f"    corrected_form: {_yaml_str(c.note)}",
    ]
    return "\n".join(lines)


def species_block() -> str:
    parts = [BEGIN]
    for name, module in MODULES.items():
        table: dict[str, Cited] = module.TABLE
        for c in table.values():
            parts.append(_record(name, c))
    parts.append(END)
    return "\n".join(parts) + "\n"


def render(existing: str) -> str:
    block = species_block()
    if BEGIN in existing and END in existing:
        head, rest = existing.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        tail = tail.lstrip("\n")
        return head + block + tail
    return existing.rstrip("\n") + "\n" + block


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--check", action="store_true", help="exit 1 if the species block is stale")
    parser.add_argument("--path", type=Path, default=ledger_path())
    args = parser.parse_args(argv)
    existing = args.path.read_text(encoding="utf-8") if args.path.exists() else "records:\n"
    rendered = render(existing)
    if args.check:
        if rendered != existing:
            print(f"{args.path}: species block is stale; run tools/ledger_from_tables.py", file=sys.stderr)
            return 1
        print(f"{args.path}: species block is current")
        return 0
    args.path.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
