"""The catalogue of displayed quantities and their provenance (PLAN.md Sections 14.1 rule 3, 14.5; Section 9.11 row
"Provenance coverage").

Every number or formula a level shows is a :class:`Quantity` here: a plain-language label (what a newcomer reads first),
the physics term and symbol (what an expert scans for), the unit, the zoom level it first appears at, the Part II section
that governs it and the ledger id its chip resolves to. The static test of Section 9.11 is the set difference between the
ledger ids used here and the ledger: a quantity whose id the ledger lacks fails the build. View-models emit
:class:`Shown` values that name their quantity, so a screen cannot show a number without a chip (Section 14.1: "A quantity
without a tag is a bug").
"""

from __future__ import annotations

from dataclasses import dataclass

Level = int


@dataclass(frozen=True)
class Quantity:
    id: str
    label: str
    """Plain language first (Section 14.5 "Units and conventions"; the ui-ux rule of plain-language labels)."""
    term: str
    """The physics term and symbol the label expands to on hover."""
    unit: str
    level: Level
    section: str
    """The Part II (or Section 13) subsection the explain panel opens."""
    ledger_id: str


@dataclass(frozen=True)
class Shown:
    """A displayed value with the quantity it is an instance of (and therefore its chip)."""

    quantity: str
    value: float | int | str | bool | None
    detail: str = ""

    def __post_init__(self) -> None:
        if self.quantity not in CATALOGUE:
            raise KeyError(
                f"{self.quantity!r} is not in the catalogue: add it with its ledger id before showing it"
            )


def _q(id: str, label: str, term: str, unit: str, level: int, section: str, ledger_id: str) -> Quantity:
    return Quantity(id, label, term, unit, level, section, ledger_id)


CATALOGUE: dict[str, Quantity] = {
    q.id: q
    for q in (
        # ---- Level 0, the machine --------------------------------------------------------------------------------------
        _q("shots", "Repetitions of the experiment", "shots N", "", 0, "3.4", "conv.shot_blocks_per_sample"),
        _q(
            "count",
            "How many times this outcome came out",
            "count n_x",
            "",
            0,
            "8.6",
            "conv.result_bit_order",
        ),
        _q(
            "probability",
            "Fraction of repetitions with this outcome",
            "estimated probability p_x = n_x/N",
            "",
            0,
            "8.6",
            "conv.result_bit_order",
        ),
        _q(
            "error_bar",
            "Statistical uncertainty of the fraction",
            "sqrt(p (1 - p)/n_eff)",
            "",
            0,
            "3.4",
            "conv.effective_sample_size",
        ),
        _q(
            "target_probability",
            "What an ideal machine would give",
            "|<x|U|0>|^2 of the compiled circuit",
            "",
            0,
            "7.2",
            "conv.compiler_frame_absorption",
        ),
        _q(
            "bitstring",
            "The outcome as bits, qubit 0 rightmost",
            "bitstring, qubit0_lsb",
            "",
            0,
            "13",
            "conv.result_bit_order",
        ),
        _q(
            "herald",
            "A flag the machine raised on this repetition",
            "herald bits: collision, dark or lost ion, count anomaly",
            "",
            0,
            "6.7",
            "conv.collision_outcomes",
        ),
        _q(
            "spam_eps_b",
            "Chance a bright ion is read as dark",
            "eps_B",
            "",
            0,
            "8.4",
            "conv.readout_figure_of_merit",
        ),
        _q(
            "spam_eps_d",
            "Chance a dark ion is read as bright",
            "eps_D",
            "",
            0,
            "8.4",
            "conv.readout_figure_of_merit",
        ),
        _q(
            "prep_error",
            "Chance the ion did not start in |0>",
            "preparation error",
            "",
            0,
            "4.2.6",
            "conv.preparation_stage_order",
        ),
        _q(
            "photon_count",
            "Photons the detector counted from this ion",
            "n per ion per shot",
            "counts",
            0,
            "8.2",
            "conv.readout_chain_exact",
        ),
        _q(
            "detection_window",
            "How long the detector looked",
            "t_det",
            "s",
            0,
            "8.3",
            "conv.readout_detected_line",
        ),
        _q(
            "threshold",
            "Counts above which the ion is called bright",
            "n_c (half-integer)",
            "counts",
            0,
            "8.3",
            "anchor.m5.myerson_optimum_and_recursion",
        ),
        _q(
            "detected_rate",
            "Photons per second from a bright ion",
            "eps_sys R_o",
            "1/s",
            0,
            "8.1",
            "conv.detection_efficiency_once",
        ),
        _q(
            "background_rate",
            "Stray counts per second",
            "R_bg",
            "1/s",
            0,
            "8.1",
            "conv.detection_efficiency_once",
        ),
        _q("species", "The atom", "ion species and mass", "", 0, "4.5", "conv.mass_ion"),
        _q(
            "ion_position",
            "Where the ion sits in the trap",
            "equilibrium position",
            "m",
            0,
            "4.1.2",
            "anchor.trap.james_spectrum",
        ),
        _q(
            "mode_frequency",
            "How fast the ions vibrate together in this mode",
            "omega_m/2pi",
            "Hz",
            0,
            "4.1.3",
            "conv.mode_index",
        ),
        _q(
            "secular_frequency",
            "Trap stiffness along one axis",
            "secular frequency omega/2pi",
            "Hz",
            0,
            "4.1.1",
            "conv.rf_amplitude_pseudopotential",
        ),
        _q(
            "qubit_frequency",
            "The qubit's transition frequency",
            "omega_0/2pi",
            "Hz",
            0,
            "4.5.1",
            "conv.frequencies",
        ),
        _q("field", "Magnetic field at the ions", "B", "G", 0, "4.5.1", "conv.curvature_naming"),
        _q(
            "gate_error_estimate",
            "Closed-form estimate of this gate's error",
            "Section 9.6 scales, summed",
            "",
            0,
            "9.6",
            "anchor.m6.bell_state",
        ),
        _q(
            "gate_error_tomography",
            "Measured error of this gate (process tomography)",
            "1 - F_avg",
            "",
            0,
            "6.8",
            "conv.gate_fidelity_measure",
        ),
        _q(
            "native_gate_set",
            "Operations the machine can do directly",
            "GPi, GPi2, MS, ZZ, virtual RZ",
            "",
            0,
            "7.1",
            "conv.gate_parameters",
        ),
        _q(
            "device_hash",
            "Fingerprint of every device parameter",
            "Device.hash()",
            "",
            0,
            "Appendix E",
            "conv.device_hash",
        ),
        _q("seed", "The random seed the run used", "root SeedSequence", "", 0, "3.4", "conv.seed_keys"),
        _q(
            "fidelity_level",
            "How exactly the machine was simulated",
            "JOINT_EXACT or GATE_LOCAL",
            "",
            0,
            "5.4",
            "anchor.m9a.gate_local_bell",
        ),
        _q(
            "heating_rate",
            "How fast a mode heats up",
            "n_dot",
            "quanta/s",
            0,
            "4.1.5",
            "conv.heating_rate_meaning",
        ),
        _q(
            "motional_dephasing",
            "How long the motion keeps its phase",
            "tau_mot",
            "s",
            0,
            "6.2",
            "conv.motional_dephasing_from_rf_noise",
        ),
        _q("beam_power", "Laser power in this beam", "P", "W", 0, "4.5.4", "conv.rabi_from_intensity"),
        _q(
            "beam_waist",
            "How tightly the beam is focused",
            "w_0",
            "m",
            0,
            "4.5.4",
            "conv.rabi_from_intensity",
        ),
        _q(
            "wavelength",
            "The laser's colour",
            "vacuum wavelength lambda",
            "m",
            0,
            "4.5.2",
            "conv.wavelengths_vacuum",
        ),
        _q(
            "polarization",
            "How the light's field oscillates",
            "Jones vector",
            "",
            0,
            "4.5.3",
            "conv.polarization_components",
        ),
        _q(
            "detector_efficiency",
            "Fraction of photons the detector catches",
            "eps_sys",
            "",
            0,
            "8.1",
            "conv.detection_efficiency_once",
        ),
        _q(
            "register_fidelity",
            "Overlap of the machine's final state with the ideal one",
            "<ideal| rho |ideal>",
            "",
            0,
            "9.6",
            "anchor.m6.bell_state",
        ),
        # ---- Level 1, the circuit --------------------------------------------------------------------------------------
        _q(
            "native_gate",
            "One operation the machine plays",
            "GPi(phi), GPi2(phi), MS(phi0, phi1, theta), ZZ(theta)",
            "rad",
            1,
            "7.6",
            "conv.gate_parameters",
        ),
        _q(
            "gate_unitary",
            "The matrix this gate is meant to apply",
            "target unitary U",
            "",
            1,
            "7.6",
            "conv.native_ms_matrix",
        ),
        _q(
            "gate_duration",
            "How long the gate takes",
            "t_gate",
            "s",
            1,
            "7.3",
            "conv.drive_coefficient_and_phase_continuity",
        ),
        _q(
            "rabi_frequency",
            "How fast the laser flips the qubit",
            "Omega/2pi",
            "Hz",
            1,
            "4.3.2",
            "conv.rabi_frequency",
        ),
        _q(
            "entangling_angle",
            "How much the two qubits were entangled",
            "chi",
            "rad",
            1,
            "4.4.1",
            "conv.entangling_angle",
        ),
        _q(
            "phase_frame",
            "A rotation the machine bookkeeps instead of playing",
            "virtual-Z frame theta, phi -> phi - theta",
            "rad",
            1,
            "7.6",
            "conv.virtual_z_propagation",
        ),
        _q(
            "stark_frame",
            "Frame update that cancels the laser's own level shift",
            "compensated light-shift frame",
            "rad",
            1,
            "7.5",
            "conv.stark_compensation",
        ),
        _q(
            "population",
            "Probability of each computational state",
            "diag(rho)",
            "",
            1,
            "5.7",
            "conv.computational_ordering",
        ),
        _q(
            "bloch_vector",
            "The qubit's state as an arrow",
            "(<X>, <Y>, <Z>)",
            "",
            1,
            "4.3.4",
            "conv.computational_ordering",
        ),
        _q(
            "pauli_expectation",
            "Average of a Pauli measurement",
            "<P>",
            "",
            1,
            "5.7",
            "conv.computational_ordering",
        ),
        _q(
            "purity",
            "How much of the state is a single pure state",
            "Tr rho^2",
            "",
            1,
            "5.4",
            "conv.computational_ordering",
        ),
        _q(
            "state_fidelity",
            "Overlap of the register with its target after this gate",
            "<target| rho |target>",
            "",
            1,
            "9.6",
            "conv.gate_fidelity_measure",
        ),
        _q(
            "compile_residual",
            "How closely the native gates reproduce the requested one",
            "max |U_block - e^{i a} U_target|",
            "",
            1,
            "7.2",
            "conv.compiler_single_qubit_decomposition",
        ),
        _q(
            "channel_infidelity",
            "Average error of the gate as a channel",
            "1 - F_avg",
            "",
            1,
            "6.8",
            "conv.gate_fidelity_measure",
        ),
        _q(
            "depolarizing_rate",
            "The gate's error as a depolarizing rate",
            "eps",
            "",
            1,
            "6.8",
            "conv.depolarizing_normalization",
        ),
        _q(
            "pauli_twirl",
            "The gate's error as Pauli flip probabilities",
            "p_P",
            "",
            1,
            "6.8",
            "conv.depolarizing_normalization",
        ),
        # ---- Level 2, the schedule -------------------------------------------------------------------------------------
        _q(
            "tone_detuning",
            "How far the laser tone is from the qubit frequency",
            "mu (from the carrier)",
            "Hz",
            2,
            "4.3.1",
            "conv.detuning_symbols",
        ),
        _q(
            "tone_envelope",
            "The tone's strength over time",
            "Omega(t)",
            "Hz",
            2,
            "7.4",
            "conv.rabi_frequency",
        ),
        _q("tone_phase", "The tone's phase", "phi_tone(t)", "rad", 2, "5.2", "conv.spin_motion_phases"),
        _q(
            "sideband_detuning",
            "How far the tone is from talking to this mode",
            "delta_{i,m} = mu_i - omega_m",
            "Hz",
            2,
            "4.4.1",
            "conv.detuning_symbols",
        ),
        _q(
            "waveform_segment",
            "One piece of the gate's pulse shape",
            "segment (duration, Omega, phi, mu)",
            "",
            2,
            "7.4",
            "conv.drive_coefficient_and_phase_continuity",
        ),
        _q(
            "closure_alpha",
            "Leftover motion the gate did not undo",
            "alpha_m(tau)",
            "",
            2,
            "4.4.3",
            "conv.ms_closure",
        ),
        _q(
            "chi_m",
            "This mode's share of the entangling angle",
            "chi_m",
            "rad",
            2,
            "4.4.3",
            "conv.entangling_sign",
        ),
        _q(
            "crosstalk",
            "Light meant for one ion that hits its neighbour",
            "eps_ij = Omega_j/Omega_i",
            "",
            2,
            "6.6",
            "conv.crosstalk_ratio",
        ),
        _q(
            "beam_direction",
            "Which way the light travels",
            "k_hat; Delta k = k_1 - k_2",
            "",
            2,
            "4.3.2",
            "conv.effective_wavevector",
        ),
        _q(
            "lamb_dicke",
            "How strongly light couples spin to motion",
            "eta_{i,m}",
            "",
            2,
            "4.1.7",
            "conv.lamb_dicke",
        ),
        _q(
            "stark_shift",
            "How the laser itself shifts the qubit frequency",
            "light shift",
            "Hz",
            2,
            "4.5.4",
            "conv.stark_compensation",
        ),
        _q(
            "idle",
            "A gap where nothing is played and noise acts",
            "idle interval",
            "s",
            2,
            "6.7",
            "conv.noise_routing",
        ),
        _q(
            "measurement_event",
            "When the detection light is on",
            "measure event",
            "s",
            2,
            "7.2",
            "conv.terminal_measurement_event",
        ),
        _q(
            "beat_phase",
            "Where the two-tone beat starts",
            "beat-note phase at the gate start",
            "rad",
            2,
            "7.10",
            "conv.beat_phase_at_gate_start",
        ),
        # ---- Level 3, the dynamics -------------------------------------------------------------------------------------
        _q(
            "P1",
            "Probability the qubit is in |1>",
            "P1(t) = <|1><1|>",
            "",
            3,
            "5.7",
            "conv.computational_ordering",
        ),
        _q(
            "coherence",
            "How much superposition the qubit holds",
            "|rho_01|(t)",
            "",
            3,
            "5.7",
            "conv.computational_ordering",
        ),
        _q(
            "mode_nbar",
            "Average number of vibration quanta in this mode",
            "<n_m>(t)",
            "quanta",
            3,
            "5.1",
            "conv.zero_point_energy",
        ),
        _q("alpha_m", "Where the mode is in phase space", "<a_m>(t)", "", 3, "4.4.1", "conv.ms_closure"),
        _q(
            "fock_population",
            "Probability of each vibration number",
            "P(n_m)",
            "",
            3,
            "5.3",
            "conv.fock_sum_branches",
        ),
        _q(
            "jump",
            "A random event the environment caused",
            "quantum jump (channel, time)",
            "s",
            3,
            "6.1",
            "conv.collapse_op_rate_units",
        ),
        _q(
            "noise_sample_value",
            "A slowly drifting parameter's value for this repetition",
            "quasi-static sample",
            "",
            3,
            "6.1",
            "conv.noise_provenance",
        ),
        _q(
            "debye_waller",
            "How thermal motion weakens the laser coupling",
            "Debye-Waller factor",
            "",
            3,
            "5.2",
            "conv.frozen_spectator_shot_sample",
        ),
        _q(
            "concurrence",
            "How entangled the two qubits are",
            "concurrence C(rho)",
            "",
            3,
            "4.4.1",
            "conv.entangling_angle",
        ),
        # ---- the numerics panel ----------------------------------------------------------------------------------------
        _q(
            "dimension",
            "Size of the simulated state space",
            "joint dimension prod dims",
            "",
            3,
            "5.1",
            "conv.space_declaration_before_allocation",
        ),
        _q(
            "truncation_cap",
            "Highest vibration number the simulation keeps",
            "d_m = n_max + 1",
            "",
            3,
            "5.5",
            "conv.mode_dimension_max",
        ),
        _q(
            "boundary_population",
            "Population that reached the cut-off",
            "top two Fock levels' population",
            "",
            3,
            "5.5",
            "conv.boundary_threshold_is_branch_scaled_on_both_sides",
        ),
        _q(
            "margin",
            "Spare vibration levels above what was used",
            "cap margin (levels)",
            "levels",
            3,
            "5.1.1",
            "conv.oracle_margin_rule",
        ),
        _q(
            "mode_class",
            "How each mode was treated",
            "resolved / frozen / dropped / enr",
            "",
            3,
            "5.2",
            "conv.mode_classes_and_tolerances",
        ),
        _q(
            "integrator",
            "The differential-equation solver used",
            "dop853 -> vern9 ladder",
            "",
            3,
            "5.3",
            "conv.solver_integrators",
        ),
        _q(
            "tolerance",
            "The solver's error tolerances",
            "(atol, rtol)",
            "",
            3,
            "5.3",
            "conv.large_mode_atol_floor",
        ),
        _q(
            "convergence",
            "Does the answer change when the solver is pushed harder?",
            "Section 9.9 regime",
            "",
            3,
            "5.5",
            "conv.section_9_9_convergence_regime",
        ),
        _q(
            "trajectories",
            "Random histories averaged",
            "trajectories",
            "",
            3,
            "3.4",
            "conv.trajectory_count_two_phases",
        ),
        _q(
            "branches",
            "Initial states summed exactly",
            "Fock-sum branches",
            "",
            3,
            "5.3",
            "conv.fock_sum_branches",
        ),
        _q(
            "samples",
            "Draws of the slowly drifting parameters",
            "quasi-static samples",
            "",
            3,
            "3.4",
            "conv.shot_blocks_per_sample",
        ),
        _q(
            "wall_time",
            "How long the computer took",
            "wall time",
            "s",
            3,
            "11.1",
            "anchor.m9b.cost_model_constants",
        ),
        _q(
            "norm_deficit",
            "How much total probability the solver lost or gained",
            "1 - Tr rho (the integrator runs unnormalized, Section 5.3)",
            "",
            3,
            "5.3",
            "conv.solver_integrators",
        ),
        _q(
            "frozen_contribution",
            "What the frozen spectator modes would have contributed",
            "|alpha|^2 (2 nbar + 1), chi",
            "",
            3,
            "5.2",
            "conv.mode_classes_and_tolerances",
        ),
        _q(
            "dropped_contribution",
            "What the dropped modes would have contributed",
            "sum |alpha|^2 (2 nbar + 1), sum |chi|",
            "",
            3,
            "11.3",
            "conv.dropped_mode_has_no_dynamics",
        ),
    )
}


def quantity(id: str) -> Quantity:
    return CATALOGUE[id]


def ledger_ids() -> frozenset[str]:
    """Every ledger id the catalogue resolves to (the left side of Section 9.11's set difference)."""
    return frozenset(q.ledger_id for q in CATALOGUE.values())


def by_level(level: int) -> tuple[Quantity, ...]:
    return tuple(q for q in CATALOGUE.values() if q.level == level)


__all__ = ["CATALOGUE", "Quantity", "Shown", "by_level", "ledger_ids", "quantity"]
